-- MySQL Script generated by MySQL Workbench
-- Thu May  9 12:45:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema joohle
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema joohle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `joohle` DEFAULT CHARACTER SET utf8 ;
USE `joohle` ;

-- -----------------------------------------------------
-- Table `joohle`.`joohle_difficulty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joohle`.`joohle_difficulty` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `deleted_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joohle`.`joohle_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joohle`.`joohle_test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `max_attempts` INT NOT NULL,
  `question_amount` INT NOT NULL,
  `shuffle` TINYINT NOT NULL,
  `required_password` TINYINT NOT NULL,
  `password` VARCHAR(255) NULL,
  `joohle_difficulty_id` INT NOT NULL,
  `deleted_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_joohle_test_joohle_difficulty_idx` (`joohle_difficulty_id` ASC),
  CONSTRAINT `fk_joohle_test_joohle_difficulty`
    FOREIGN KEY (`joohle_difficulty_id`)
    REFERENCES `joohle`.`joohle_difficulty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joohle`.`joohle_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joohle`.`joohle_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `deleted_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joohle`.`joohle_attempt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joohle`.`joohle_attempt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `max_score` DOUBLE NOT NULL,
  `score` DOUBLE NOT NULL,
  `user_id` INT NOT NULL,
  `joohle_test_id` INT NOT NULL,
  `started_at` DATETIME NOT NULL,
  `finished_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_joohle_attempt_joohle_test1_idx` (`joohle_test_id` ASC),
  CONSTRAINT `fk_joohle_attempt_joohle_test1`
    FOREIGN KEY (`joohle_test_id`)
    REFERENCES `joohle`.`joohle_test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joohle`.`joohle_question_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joohle`.`joohle_question_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NULL,
  `deleted_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joohle`.`joohle_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joohle`.`joohle_question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `max_score` DOUBLE NOT NULL,
  `joohle_test_id` INT NOT NULL,
  `joohle_question_type_id` INT NOT NULL,
  `deleted_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_joohle_question_joohle_test1_idx` (`joohle_test_id` ASC),
  INDEX `fk_joohle_question_joohle_question_type1_idx` (`joohle_question_type_id` ASC),
  CONSTRAINT `fk_joohle_question_joohle_test1`
    FOREIGN KEY (`joohle_test_id`)
    REFERENCES `joohle`.`joohle_test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_joohle_question_joohle_question_type1`
    FOREIGN KEY (`joohle_question_type_id`)
    REFERENCES `joohle`.`joohle_question_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joohle`.`joohle_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joohle`.`joohle_answer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `answer` VARCHAR(255) NOT NULL,
  `score` DOUBLE NOT NULL,
  `joohle_question_id` INT NOT NULL,
  `deleted_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_joohle_answer_joohle_question1_idx` (`joohle_question_id` ASC),
  CONSTRAINT `fk_joohle_answer_joohle_question1`
    FOREIGN KEY (`joohle_question_id`)
    REFERENCES `joohle`.`joohle_question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joohle`.`joohle_test_has_joohle_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joohle`.`joohle_test_has_joohle_category` (
  `joohle_test_id` INT NOT NULL,
  `joohle_category_id` INT NOT NULL,
  `deleted_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`joohle_test_id`, `joohle_category_id`),
  INDEX `fk_joohle_test_has_joohle_category_joohle_category1_idx` (`joohle_category_id` ASC),
  INDEX `fk_joohle_test_has_joohle_category_joohle_test1_idx` (`joohle_test_id` ASC),
  CONSTRAINT `fk_joohle_test_has_joohle_category_joohle_test1`
    FOREIGN KEY (`joohle_test_id`)
    REFERENCES `joohle`.`joohle_test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_joohle_test_has_joohle_category_joohle_category1`
    FOREIGN KEY (`joohle_category_id`)
    REFERENCES `joohle`.`joohle_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
